" All system-wide defaults are set in $VIMRUNTIME/debian.vim and sourced by
" the call to :runtime you can find below.  If you wish to change any of those
" settings, you should do it in this file (/etc/vim/vimrc), since debian.vim
" will be overwritten everytime an upgrade of the vim packages is performed.
" It is recommended to make changes after sourcing debian.vim since it alters
" the value of the 'compatible' option.
"
" Nik
syntax on
set smartcase
set mouse-=a
set showcmd		" Show (partial) command in status line.
set nobackup          " do not keep a backup file, use versions instead
set ts=4
set noswapfile
set bg=dark
